import { Hospital } from "src/app/Models/hospital";
import { DonorInfo } from "../../Models/donor";

export const DonorData: DonorInfo[] = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    password: "password123",
    confirmPassword: "password123",
    contact: "+1234567890",
    gender: "Male",
    dob: "15-05-1990",
    bloodgroup: "A+",
    medical_history: "None",
    unit: 3,
    requestedDate: "",
    created_at: "2024-08-01",
    updated_at: "2024-08-10",
    status: "Rejected",
    city: "New York",
    country: "USA",
    address: "123 Elm Street"
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    password: "mypassword",
    confirmPassword: "mypassword",
    contact: "+0987654321",
    gender: "Female",
    dob: "22-12-1985",
    bloodgroup: "B-",
    medical_history: "Diabetes",
    unit: 2,
    requestedDate: "",
    created_at: "2024-08-02",
    updated_at: "2024-08-11",
    status: "",
    city: "Los Angeles",
    country: "USA",
    address: "456 Oak Avenue"
  },
  // {
  //   id: 3,
  //   name: "Michael Johnson",
  //   email: "michael.johnson@example.com",
  //   password: "password789",
  //   confirmPassword: "password789",
  //   contact: "+1111222233",
  //   gender: "Male",
  //   dob: "1992-07-08",
  //   bloodgroup: "O+",
  //   medical_history: "Hypertension",
  //   unit: 4,
  //   requestedDate: "2024-08-12",
  //   created_at: "2024-08-03",
  //   updated_at: "2024-08-12",
  //   status: "Active",
  //   city: "Chicago",
  //   country: "USA",
  //   address: "789 Maple Road"
  // },
  // {
  //   id: 4,
  //   name: "Emily Davis",
  //   email: "emily.davis@example.com",
  //   password: "securepass",
  //   confirmPassword: "securepass",
  //   contact: "+4444555566",
  //   gender: "Female",
  //   dob: "1998-03-30",
  //   bloodgroup: "AB+",
  //   medical_history: "None",
  //   unit: 1,
  //   requestedDate: "2024-08-13",
  //   created_at: "2024-08-04",
  //   updated_at: "2024-08-13",
  //   status: "Active",
  //   city: "Houston",
  //   country: "USA",
  //   address: "321 Pine Lane"
  // },
  // {
  //   id: 5,
  //   name: "Chris Brown",
  //   email: "chris.brown@example.com",
  //   password: "password456",
  //   confirmPassword: "password456",
  //   contact: "+3333444455",
  //   gender: "Male",
  //   dob: "1980-11-11",
  //   bloodgroup: "B+",
  //   medical_history: "Asthma",
  //   unit: 3,
  //   requestedDate: "2024-08-14",
  //   created_at: "2024-08-05",
  //   updated_at: "2024-08-14",
  //   status: "Inactive",
  //   city: "Phoenix",
  //   country: "USA",
  //   address: "654 Birch Boulevard"
  // },
  // {
  //   id: 6,
  //   name: "Lisa White",
  //   email: "lisa.white@example.com",
  //   password: "mypass123",
  //   confirmPassword: "mypass123",
  //   contact: "+6666777788",
  //   gender: "Female",
  //   dob: "1995-09-19",
  //   bloodgroup: "O-",
  //   medical_history: "None",
  //   unit: 2,
  //   requestedDate: "2024-08-15",
  //   created_at: "2024-08-06",
  //   updated_at: "2024-08-15",
  //   status: "Active",
  //   city: "San Diego",
  //   country: "USA",
  //   address: "987 Cedar Court"
  // },
  // {
  //   id: 7,
  //   name: "David Wilson",
  //   email: "david.wilson@example.com",
  //   password: "mypassword456",
  //   confirmPassword: "mypassword456",
  //   contact: "+7777888899",
  //   gender: "Male",
  //   dob: "1983-06-04",
  //   bloodgroup: "A-",
  //   medical_history: "None",
  //   unit: 4,
  //   requestedDate: "2024-08-16",
  //   created_at: "2024-08-07",
  //   updated_at: "2024-08-16",
  //   status: "Active",
  //   city: "Dallas",
  //   country: "USA",
  //   address: "123 Willow Drive"
  // },
  // {
  //   id: 8,
  //   name: "Sophia Taylor",
  //   email: "sophia.taylor@example.com",
  //   password: "securepassword",
  //   confirmPassword: "securepassword",
  //   contact: "+8888999900",
  //   gender: "Female",
  //   dob: "2000-02-28",
  //   bloodgroup: "AB-",
  //   medical_history: "None",
  //   unit: 1,
  //   requestedDate: "2024-08-17",
  //   created_at: "2024-08-08",
  //   updated_at: "2024-08-17",
  //   status: "Inactive",
  //   city: "San Jose",
  //   country: "USA",
  //   address: "456 Spruce Circle"
  // },
  // {
  //   id: 9,
  //   name: "James Anderson",
  //   email: "james.anderson@example.com",
  //   password: "password654",
  //   confirmPassword: "password654",
  //   contact: "+9999000011",
  //   gender: "Male",
  //   dob: "1997-04-16",
  //   bloodgroup: "B+",
  //   medical_history: "None",
  //   unit: 3,
  //   requestedDate: "2024-08-18",
  //   created_at: "2024-08-09",
  //   updated_at: "2024-08-18",
  //   status: "Active",
  //   city: "Austin",
  //   country: "USA",
  //   address: "789 Redwood Street"
  // },
  // {
  //   id: 10,
  //   name: "Olivia Martinez",
  //   email: "olivia.martinez@example.com",
  //   password: "pass789",
  //   confirmPassword: "pass789",
  //   contact: "+1111222233",
  //   gender: "Female",
  //   dob: "1999-08-25",
  //   bloodgroup: "O+",
  //   medical_history: "None",
  //   unit: 2,
  //   requestedDate: "2024-08-19",
  //   created_at: "2024-08-10",
  //   updated_at: "2024-08-19",
  //   status: "Active",
  //   city: "Jacksonville",
  //   country: "USA",
  //   address: "321 Ash Avenue"
  // },
  // {
  //   id: 11,
  //   name: "Ethan Thomas",
  //   email: "ethan.thomas@example.com",
  //   password: "mypassword789",
  //   confirmPassword: "mypassword789",
  //   contact: "+2222333344",
  //   gender: "Male",
  //   dob: "1991-01-12",
  //   bloodgroup: "A+",
  //   medical_history: "Allergies",
  //   unit: 4,
  //   requestedDate: "2024-08-20",
  //   created_at: "2024-08-11",
  //   updated_at: "2024-08-20",
  //   status: "Inactive",
  //   city: "Columbus",
  //   country: "USA",
  //   address: "654 Pine Road"
  // },
  // {
  //   id: 12,
  //   name: "Ava Hernandez",
  //   email: "ava.hernandez@example.com",
  //   password: "securepass123",
  //   confirmPassword: "securepass123",
  //   contact: "+5555666677",
  //   gender: "Female",
  //   dob: "1988-10-30",
  //   bloodgroup: "B-",
  //   medical_history: "Hypertension",
  //   unit: 1,
  //   requestedDate: "2024-08-21",
  //   created_at: "2024-08-12",
  //   updated_at: "2024-08-21",
  //   status: "Active",
  //   city: "Charlotte",
  //   country: "USA",
  //   address: "987 Walnut Drive"
  // },
  // {
  //   id: 13,
  //   name: "Alexander Moore",
  //   email: "alexander.moore@example.com",
  //   password: "password012",
  //   confirmPassword: "password012",
  //   contact: "+3333444455",
  //   gender: "Male",
  //   dob: "1986-02-17",
  //   bloodgroup: "O+",
  //   medical_history: "Asthma",
  //   unit: 2,
  //   requestedDate: "2024-08-22",
  //   created_at: "2024-08-13",
  //   updated_at: "2024-08-22",
  //   status: "Inactive",
  //   city: "San Francisco",
  //   country: "USA",
  //   address: "123 Birch Avenue"
  // },
  // {
  //   id: 14,
  //   name: "Isabella Martin",
  //   email: "isabella.martin@example.com",
  //   password: "mypassword012",
  //   confirmPassword: "mypassword012",
  //   contact: "+6666777788",
  //   gender: "Female",
  //   dob: "2002-05-06",
  //   bloodgroup: "AB+",
  //   medical_history: "None",
  //   unit: 3,
  //   requestedDate: "2024-08-23",
  //   created_at: "2024-08-14",
  //   updated_at: "2024-08-23",
  //   status: "Active",
  //   city: "Seattle",
  //   country: "USA",
  //   address: "456 Maple Boulevard"
  // },
  // {
  //   id: 15,
  //   name: "Lucas Garcia",
  //   email: "lucas.garcia@example.com",
  //   password: "securepassword456",
  //   confirmPassword: "securepassword456",
  //   contact: "+7777888899",
  //   gender: "Male",
  //   dob: "1993-11-22",
  //   bloodgroup: "B+",
  //   medical_history: "None",
  //   unit: 4,
  //   requestedDate: "2024-08-24",
  //   created_at: "2024-08-15",
  //   updated_at: "2024-08-24",
  //   status: "Active",
  //   city: "Denver",
  //   country: "USA",
  //   address: "789 Cedar Avenue"
  // }
]

export const hospitalData: Hospital[] = [
  {
      id: 1,
      name: "City Health Hospital",
      contact: "123-456-7890",
      email: "info@cityhealth.com",
      address: "123 Main St, Downtown",
      city: "Metropolis",
      country: "Country A",
      registrationDate: new Date("2022-01-15"),
      created_at: "2022-01-15",
      updated_at: "2022-01-15",
      bloodRequests: [
          {
              requestId: "R001",
              requestDate: new Date("2024-08-01"),
              bloodGroup: "A+",
              unitsRequested: 10,
              disease: 'BP',
              unitsGiven: '',
              status: ""
          },
          {
              requestId: "R002",
              requestDate: new Date("2024-08-05"),
              bloodGroup: "B+",
              unitsRequested: 5,
              disease:'Sugar',
              unitsGiven: '',
              status: "Accepted"
          }
      ]
  },
  {
      id: 2,
      name: "Green Valley Hospital",
      contact: "987-654-3210",
      email: "contact@greenvalley.com",
      address: "456 Oak St, Suburbia",
      city: "Gotham",
      country: "Country B",
      registrationDate: new Date("2021-11-20"),
      created_at: "2022-01-15",
      updated_at: "2022-01-15",
      bloodRequests: [
          {
              requestId: "R003",
              requestDate: new Date("2024-07-22"),
              bloodGroup: "O-",
              unitsRequested: 8,
              status: "",
              disease:'Sugar',
              unitsGiven: '',
          }
      ]
  },
  {
      id: 3,
      name: "Sunrise Medical Center",
      contact: "555-789-1234",
      email: "support@sunrisemedical.com",
      address: "789 Pine St, Uptown",
      city: "Star City",
      country: "Country C",
      registrationDate: new Date("2023-03-05"),
      created_at: "2022-01-15",
      updated_at: "2022-01-15",
      bloodRequests: [
          {
              requestId: "R004",
              requestDate: new Date("2024-08-10"),
              bloodGroup: "AB+",
              unitsRequested: 15,
              disease:'Sugar',
              unitsGiven: '',
              status: "Rejected"
          },
          {
              requestId: "R005",
              requestDate: new Date("2024-08-12"),
              bloodGroup: "B-",
              unitsRequested: 7,
              disease:'Sugar',
              unitsGiven: '',
              status: "Accepted"
          }
      ]
  },
  {
      id: 4,
      name: "Riverdale General Hospital",
      contact: "444-555-6666",
      email: "info@riverdalegeneral.com",
      address: "321 Maple St, Riverside",
      city: "Central City",
      country: "Country D",
      registrationDate: new Date("2020-07-19"),
      created_at: "2022-01-15",
      updated_at: "2022-01-15",
      bloodRequests: [
          {
              requestId: "R006",
              requestDate: new Date("2024-08-14"),
              bloodGroup: "O+",
              unitsRequested: 12,
              disease:'Sugar',
              unitsGiven: '',
              status: ""
          }
      ]
  },
  {
      id: 5,
      name: "Harmony Healthcare",
      contact: "222-333-4444",
      email: "contact@harmonyhealth.com",
      address: "654 Cedar St, Harmony District",
      city: "Bay City",
      country: "Country E",
      registrationDate: new Date("2022-12-01"),
      created_at: "2022-01-15",
      updated_at: "2022-01-15",
      bloodRequests: [
          {
              requestId: "R007",
              requestDate: new Date("2024-08-07"),
              bloodGroup: "A-",
              unitsRequested: 9,
              disease:'Sugar',
              unitsGiven: '',
              status: "Accepted"
          }
      ]
  }
];

export interface Appointment {
  appointmentId: string;       // Unique identifier for the appointment (could be a UUID or auto-incremented ID)
  donorId: string;             // Foreign key linking to the Donors table
  appointmentDate: Date;       // Date and time of the scheduled appointment
  donationCenter: string;      // Name or ID of the donation center where the appointment is scheduled
  status: AppointmentStatus;   // Status of the appointment (e.g., "Scheduled", "Accepted", "Cancelled", "Rescheduled")
  notes?: string;              // Optional field for any additional notes (e.g., special instructions)
}

// Example of an enum to represent possible statuses
export enum AppointmentStatus {
  Scheduled = "Scheduled",
  Accepted = "Accepted",
  Cancelled = "Cancelled",
  Rescheduled = "Rescheduled"
}